# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ReactNativeSampleApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
  pod 'Onfido', '7.1.0'

  # Pods for ReactNativeSampleApp

  target 'ReactNativeSampleApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ReactNativeSampleAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

