# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

react_native_path = '../node_modules/react-native'

target 'ReactNativeSampleApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  pod 'Onfido'

  pod 'AFNetworking'

  target 'ReactNativeSampleAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

    post_install do |installer|
        installer.pods_project.targets.each do |target|
            if target.name == 'Alamofire'
                target.build_configurations.each do |config|
                    config.build_settings['SWIFT_VERSION'] = '4.1'
                end
            elsif target.name == 'Swinject'
                target.build_configurations.each do |config|
                    config.build_settings['SWIFT_VERSION'] = '4.1'
                end
            end
        end
    end
end
